services:
  mariadb:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "2222:22"
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mariadb_data:/tmp/mysql
    environment:
      - TZ=UTC
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "2223:22"
      - "8080:80"
    restart: unless-stopped
    volumes:
      - nginx_data:/tmp/nginx
    environment:
      - TZ=UTC

volumes:
  mariadb_data:
  nginx_data:
